// Generated by scripts/generate-note-transport-limits.py. Do not edit by hand.
#![allow(dead_code)]

pub const DEFAULT_NOTE_PAGE_ITEMS: u32 = 50;
pub const MIN_NOTE_PAGE_ITEMS: u32 = 1;
pub const MAX_NOTE_PAGE_ITEMS: u32 = 100;
pub const MAX_NOTE_CURSOR_BYTES: usize = 512;
pub const MAX_NOTE_MUTATION_REQUEST_BYTES: usize = 6_291_456;
pub const MAX_NOTE_ENCODED_PAGE_BYTES: usize = 7_340_032;
pub const MAX_NOTE_DECOMPRESSED_PAGE_BYTES: usize = 8_388_608;
pub const MAX_NOTE_COLLECTION_PAGES: usize = 100;
pub const MAX_NOTE_COLLECTION_ITEMS: usize = 10_000;
pub const MAX_NOTE_COLLECTION_ENCODED_BYTES: usize = 67_108_864;
