// Generated by scripts/generate-attachment-transport-limits.py. Do not edit by hand.

pub const MAX_ATTACHMENT_CIPHERTEXT_BYTES: u64 = 10_485_760;
pub const MAX_ATTACHMENT_PLAINTEXT_BYTES: u64 = 10_485_705;
