// Generated by scripts/generate-attachment-transport-limits.py. Do not edit by hand.

export const MAX_ATTACHMENT_CIPHERTEXT_BYTES = 10_485_760
export const MAX_ATTACHMENT_PLAINTEXT_BYTES = 10_485_705
